apiVersion: v1
kind: ReplicationController
metadata:
  name: javarc
  namespace: flipkartns
spec:
  replicas: 3
  selector:
    app: javaapp
  template:
    metadata:
      name: javapod
      labels:
        app: javaapp
    spec:
      containers:
      - name: java-web-app
        image: pavandevopsdocker/pizza:1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: replicasvc
  namespace: flipkartns
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
  - port: 80
    targetPort: 8080
